# Generated by Django 3.1.5 on 2021-02-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raildata', '0009_auto_20210227_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
