# Generated by Django 3.1.5 on 2021-03-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('Feedback', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passsword', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfPassenger', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('Source', models.CharField(max_length=30)),
                ('Destination', models.CharField(max_length=30)),
                ('ticketStatus', models.CharField(max_length=10)),
                ('Trainno', models.IntegerField()),
                ('Ticketno', models.IntegerField(default=1, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('arrivaltime', models.CharField(max_length=50)),
                ('departuretime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('Trainno', models.IntegerField(primary_key=True, serialize=False)),
                ('arrivaltime', models.TimeField()),
                ('departuretime', models.TimeField()),
                ('Source', models.CharField(max_length=30)),
                ('Destination', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=50)),
                ('conf_pass', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.DateField()),
                ('contact', models.IntegerField()),
                ('gender', models.CharField(max_length=5)),
            ],
        ),
    ]
