# Generated by Django 3.1.5 on 2021-03-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raildata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='Ticketno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
