# Generated by Django 3.1.5 on 2021-02-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raildata', '0002_auto_20210225_1730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDetails',
        ),
    ]
