# Generated by Django 3.1.5 on 2021-02-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raildata', '0003_auto_20210225_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='age',
            field=models.DateField(),
        ),
    ]
