# Generated by Django 3.1.5 on 2021-02-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raildata', '0005_auto_20210226_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='arrivaltime',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='departuretime',
        ),
    ]
