# Generated by Django 3.1.5 on 2021-02-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raildata', '0008_remove_train_trainname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrivaltime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='departuretime',
            field=models.TimeField(),
        ),
    ]
