# Generated by Django 3.1.5 on 2021-03-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raildata', '0010_train_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=300)),
            ],
        ),
    ]
