# Generated by Django 3.1.5 on 2021-03-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raildata', '0011_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(default='none', max_length=40),
            preserve_default=False,
        ),
    ]
